name: Build
run-name: Build ${{ github.ref_name }}
on:
  push:
    tags: [ "v*.*.*" ]
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: arc-runner-set
    strategy:
      matrix:
        goos: [ "linux", "darwin", "windows" ]
        goarch: [ "amd64", "arm64" ]
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
    steps:
      - run: |
          echo "filename=fritzcable_exporter_${GOOS}_${GOARCH}" >> "$GITHUB_ENV"
      - run: |
          echo "filename=${filename}.exe" >> "$GITHUB_ENV"
        if: matrix.goos == 'windows'
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '1.24'
      - run: |
          go build -o $filename ./cmd
          echo "filename=$filename" >> "$GITHUB_OUTPUT"
        id: compile
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.compile.outputs.filename }}
          path: |
            fritzcable_exporter_*
  release:
    runs-on: arc-runner-set
    needs: build
    if: github.ref_type == 'tag'
    permissions: 
      contents: write
    steps:
      - uses: actions/download-artifact@v5
        with:
          merge-multiple: 'true'
      - run: shasum -a 256 fritzcable_exporter_* > sha256sum.txt
      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            fritzcable_exporter_*
            sha256sum.txt